/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/QcfL8lD2b98
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Checkbox } from "@/components/ui/checkbox"
import { Button } from "@/components/ui/button"

export function MobilePhoneNumberCard() {
  return (
    (<Card className="w-full max-w-md">
      <CardHeader>
        <CardTitle>Get AI Follow-ups</CardTitle>
        <CardDescription>
          Enter your mobile number below and an AI assistant will follow up with you on important updates. Remember to
          return to the app to turn this feature off when you no longer need it.
        </CardDescription>
      </CardHeader>
      <CardContent>
        <div className="flex flex-col space-y-2">
          <div className="flex items-center space-x-2">
            <Input type="tel" placeholder="Country Code" className="flex-1 max-w-[100px]" />
            <Input type="tel" placeholder="Enter mobile number" className="flex-1" />
          </div>
          <div className="flex items-center space-x-2">
            <Checkbox id="consent" />
            <label
              htmlFor="consent"
              className="text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70">
              I consent to receive text messages
            </label>
          </div>
          <Button>Submit</Button>
        </div>
      </CardContent>
    </Card>)
  );
}
